
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Banquews)", targetNamespace = "http://Compte.bilal.org/", wsdlLocation = "http://localhost:9191/BanqueWS?wsdl")
public class Banquews_0029
    extends Service
{

    private final static URL BANQUEWS_0029_WSDL_LOCATION;
    private final static WebServiceException BANQUEWS_0029_EXCEPTION;
    private final static QName BANQUEWS_0029_QNAME = new QName("http://Compte.bilal.org/", "Banquews)");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/BanqueWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUEWS_0029_WSDL_LOCATION = url;
        BANQUEWS_0029_EXCEPTION = e;
    }

    public Banquews_0029() {
        super(__getWsdlLocation(), BANQUEWS_0029_QNAME);
    }

    public Banquews_0029(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUEWS_0029_QNAME, features);
    }

    public Banquews_0029(URL wsdlLocation) {
        super(wsdlLocation, BANQUEWS_0029_QNAME);
    }

    public Banquews_0029(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUEWS_0029_QNAME, features);
    }

    public Banquews_0029(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Banquews_0029(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://Compte.bilal.org/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Compte.bilal.org/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUEWS_0029_EXCEPTION!= null) {
            throw BANQUEWS_0029_EXCEPTION;
        }
        return BANQUEWS_0029_WSDL_LOCATION;
    }

}
